pub mod actions;
pub mod animation;
pub mod app;
pub mod components;
pub mod design;
pub mod devicons;
pub mod editor;
pub mod effects;
pub mod element;
pub mod events;
pub mod icons;
pub mod palette;
pub mod shell;
pub mod signals;
pub mod state;
pub mod style;
pub mod theme;

pub use app::run;
