if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows")
  if(CMAKE_VERSION VERSION_LESS "3.29")
    message(FATAL_ERROR "Windows presets require CMake 3.29 or newer.")
  endif()

  set(CMAKE_C_COMPILER clang-cl CACHE STRING "C compiler for Windows builds")
  set(CMAKE_CXX_COMPILER clang-cl CACHE STRING "C++ compiler for Windows builds")
  set(CMAKE_LINKER_TYPE SYSTEM CACHE STRING "Use the Visual Studio linker with clang-cl")
  set(VCPKG_TARGET_TRIPLET x64-windows-static-md CACHE STRING "vcpkg triplet for Windows builds")

  if(DEFINED ENV{VCPKG_ROOT} AND NOT "$ENV{VCPKG_ROOT}" STREQUAL "")
    include("$ENV{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake")
  else()
    message(FATAL_ERROR "Set VCPKG_ROOT before configuring on Windows.")
  endif()

  if(DEFINED ENV{QT_ROOT} AND NOT "$ENV{QT_ROOT}" STREQUAL "")
    file(TO_CMAKE_PATH "$ENV{QT_ROOT}" DIFFY_QT_ROOT)
    set(DIFFY_QT6_CONFIG_DIR "${DIFFY_QT_ROOT}/lib/cmake/Qt6")

    if(NOT EXISTS "${DIFFY_QT6_CONFIG_DIR}/Qt6Config.cmake")
      message(FATAL_ERROR
        "QT_ROOT must point to the Qt install root that contains lib/cmake/Qt6/Qt6Config.cmake.")
    endif()

    if(DEFINED CMAKE_PREFIX_PATH)
      set(DIFFY_CMAKE_PREFIX_PATH "${CMAKE_PREFIX_PATH}")
    else()
      set(DIFFY_CMAKE_PREFIX_PATH "")
    endif()
    list(PREPEND DIFFY_CMAKE_PREFIX_PATH "${DIFFY_QT_ROOT}")
    set(CMAKE_PREFIX_PATH "${DIFFY_CMAKE_PREFIX_PATH}" CACHE STRING "CMake package prefixes" FORCE)
    set(Qt6_DIR "${DIFFY_QT6_CONFIG_DIR}" CACHE PATH "Qt6 package config directory" FORCE)
  else()
    message(FATAL_ERROR "Set QT_ROOT before configuring on Windows.")
  endif()
endif()
