
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/nix/store/1m0z4ixir10fg7ba7g131js04bxgv265-cmake-4.1.2/share/cmake-4.1/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/home/rohit/.local/bin/"
      - "/home/rohit/.bun/bin/"
      - "/home/rohit/.codex/tmp/arg0/codex-arg0wGnUG2/"
      - "/home/rohit/.bun/install/global/node_modules/@openai/codex-linux-x64/vendor/x86_64-unknown-linux-musl/path/"
      - "/nix/store/b87dfjnjvg932xsw4mszjg4qmvrqzlqk-nodejs-22.22.0/bin/"
      - "/nix/store/8x49w8i0vafv34rlc6h4a0f7z0z2qpb5-git-2.53.0/bin/"
      - "/nix/store/kbw2j1vag664b3sj3rjwz9v53cqx87sb-gcc-wrapper-15.2.0/bin/"
      - "/nix/store/sca0pf46jmxva40qahkcwys5c1lvk6n2-gcc-15.2.0/bin/"
      - "/nix/store/2c48s343k15i0cmwb9cp1vi6randmzcw-glibc-2.42-51-bin/bin/"
      - "/nix/store/hlxw2q9qansq7bn52xvlb5badw3z1v8s-coreutils-9.10/bin/"
      - "/nix/store/4yi6jj75bb5hhdzpzlxfyf69d35wsf2x-binutils-wrapper-2.44/bin/"
      - "/nix/store/9nmzd62x45ayp4vmswvn6z45h6bzrsla-binutils-2.44/bin/"
      - "/nix/store/vj8m1cbj1xw2b3j55ppcby5mnchb9iml-gdb-17.1/bin/"
      - "/nix/store/dz1lv10zfqhdnpdjqbawdacd6j1328m1-lldb-21.1.8/bin/"
      - "/nix/store/x05g7ya1h7r6x0zycxgxd2i85d4h0pnv-rr-5.9.0/bin/"
      - "/nix/store/5a55fdw8da21pkd5g2pd1jkj9q06ljb5-strace-6.19/bin/"
      - "/nix/store/1m0z4ixir10fg7ba7g131js04bxgv265-cmake-4.1.2/bin/"
      - "/nix/store/4siii6hvzs9ymbq37k04vcpx6xnybz21-ninja-1.13.2/bin/"
      - "/nix/store/1nv3i8mpypy3d516f4pd95m0w72r73jy-pkg-config-wrapper-0.29.2/bin/"
      - "/nix/store/i1bhjxlrci4j824srcihrm95rxbhkf7w-lndir-1.0.5/bin/"
      - "/nix/store/ym2nazjm9vqi0md5dw03vsh9zhg4v6q9-wayland-scanner-1.24.0-bin/bin/"
      - "/nix/store/590yx3aynyhs48jyk8ip37fk1mjqfhkb-patchelf-0.15.2/bin/"
      - "/nix/store/mxylb81fv1n7skrdlrxnpbzf344mkhy4-curl-8.18.0-dev/bin/"
      - "/nix/store/3y8jfnbcv230kip514qh2wmfifihzvqp-brotli-1.2.0/bin/"
      - "/nix/store/jmbxnc0r2blyjpivvg3gabz6flyzy3bn-krb5-1.22.1-dev/bin/"
      - "/nix/store/aaa7ja0i8hjmgvx6c435h5bm5l8d2jyj-krb5-1.22.1/bin/"
      - "/nix/store/dajq3vl5b2x5ld7wxiizcf3xss2dj5fy-nghttp2-1.67.1/bin/"
      - "/nix/store/3rr54wwd3246s39mc3z9jzyj9577ik9z-libidn2-2.3.8-bin/bin/"
      - "/nix/store/9nww32bprhg1rr1qj423xdr5mwnqk93z-openssl-3.6.1-bin/bin/"
      - "/nix/store/qvxaabi4w7isbp0vxqqsx4brl5n1qnjh-libpsl-0.21.5/bin/"
      - "/nix/store/xks3v41w0rqp27a17kwkybcvr39rxpl8-zstd-1.5.7-bin/bin/"
      - "/nix/store/m27kji8vcm9hn8jyn3dxixxkgbs6p0kp-zstd-1.5.7/bin/"
      - "/nix/store/50bwm2f9bzx1vn4fbn2azgx76pqngzc2-curl-8.18.0-bin/bin/"
      - "/nix/store/6n5mc6pkgdc9sl529n9h0snvp91df7b9-libgit2-1.9.2/bin/"
      - "/nix/store/aca95j471nd9bj5q8f6zzhr1hs36cqsw-tree-sitter-0.25.10/bin/"
      - "/nix/store/1f6917ky6w2gghw63myngxr2zq2zh8rm-libxml2-2.15.1-dev/bin/"
      - "/nix/store/4krj3d6h2xpcdc6a2hphr2i4k6rab9kc-libxml2-2.15.1-bin/bin/"
      - "/nix/store/p9485gsvn63zj7jraa5viv7mzn1m5i73-libxslt-1.1.45-dev/bin/"
      - "/nix/store/5akzak6yir5qanifyrxh4fazb8vwn85y-libxslt-1.1.45-bin/bin/"
      - "/nix/store/k87a0gv4hg1zmm8j5d3ffmxyvhr13i41-sqlite-3.51.2-bin/bin/"
      - "/nix/store/x6y6khsf313j6sa6pjcv9ar0k4rkdph1-harfbuzz-12.3.0-dev/bin/"
      - "/nix/store/ja1snqi59bxqa00c95iyk9mz67gm1jbj-graphite2-1.3.14/bin/"
      - "/nix/store/q151vxaxv1l4hmf7kccgs45h0xcngagp-icu4c-76.1-dev/bin/"
      - "/nix/store/w406ywjzdrsh8qncnr22hqyf6a3rvxgk-libjpeg-turbo-3.1.3-bin/bin/"
      - "/nix/store/678ygbangkyc4yb5xm7qb4psfpk3vw4c-libpng-apng-1.6.55-dev/bin/"
      - "/nix/store/mckjxamkfdij0vy7m3m7dmhwpbmr0zwq-pcre2-10.46-dev/bin/"
      - "/nix/store/wf3ks95mgi0nspblgd9h4kkffd2dzjrd-pcre2-10.46-bin/bin/"
      - "/nix/store/n97s6g4759lfdhf7fcl01s0yy9sfkk7m-md4c-0.5.2/bin/"
      - "/nix/store/p6vpw9wvgj3l1yvw8q225a7j6f0njiwd-libproxy-0.5.12/bin/"
      - "/nix/store/j057drxjcwss3k4d6c9glkqaj5cv5wf5-dbus-1.16.2-lib/bin/"
      - "/nix/store/c9cnbxhxbagj7gfpc1g5hl4x4f8dzayv-dbus-1.16.2/bin/"
      - "/nix/store/jhb15l57qmqxck5ddd1dh2ys729vc8gb-glib-2.86.3-dev/bin/"
      - "/nix/store/md592gfars4m9madyrpj9yrq5jhckgjf-gettext-0.26/bin/"
      - "/nix/store/h2mc9v6n2rcxk53nxk6gwcg1md581idy-glib-2.86.3-bin/bin/"
      - "/nix/store/9b51f94qkn759n1m88raz4f6rmwj31fc-unixODBC-2.3.12/bin/"
      - "/nix/store/wxyn8d3m8g4fnn6xazinjwhzhzdg6wib-systemd-259/bin/"
      - "/nix/store/ilk5qzvkadnj7lx58hfinfvl7jmhriq6-util-linux-2.41.3-bin/bin/"
      - "/nix/store/vkk4sxf0f998s0nlsaz1k78zldy3qcx4-mtdev-1.1.7/bin/"
      - "/nix/store/lxwj6idzb1z8k6c4i7vq6hd8zm2krw7j-lksctp-tools-1.0.21/bin/"
      - "/nix/store/v23zbl7lbrqdlbnrmivk9jyxd7gl36b1-libselinux-3.8.1-bin/bin/"
      - "/nix/store/jxjhvx3bc62iz70dnfl2dvkbrglaf4v2-libsepol-3.8.1-bin/bin/"
      - "/nix/store/nvlwzg459z57dsac3r9g3n0glhy4bwsv-lttng-ust-2.14.0-bin/bin/"
      - "/nix/store/hk5mbqv61b0lmxnmls3anbmn7w4bbg0f-libdrm-2.4.131-bin/bin/"
      - "/nix/store/xzzk980zwrbjm5j1yrxr43q9c7cdas4l-libdatrie-2019-12-20-bin/bin/"
      - "/nix/store/374f5mfap8y7i6rzc3qnq249ym1nxfdq-freetype-2.13.3-dev/bin/"
      - "/nix/store/x8l7qzpab2gpdrp89g48mxlrsiz4f0gm-bzip2-1.0.8-bin/bin/"
      - "/nix/store/g21qfm40ppq15mmz6n8l48m5k26i8ngf-fontconfig-2.17.1-bin/bin/"
      - "/nix/store/k1gvr4prs9736r1lhqyy1plxrrvv9b4m-libxkbcommon-1.11.0/bin/"
      - "/nix/store/784p3pvhp35icmzh13rwai726j84r2dg-cups-2.4.16-dev/bin/"
      - "/nix/store/q8zb95f4m2aahbdi6jl7wh3cjwc4p855-cups-2.4.16/bin/"
      - "/nix/store/w4q31b93w262q2b75ri3jc7m3xd4i31h-qtbase-6.10.2/bin/"
      - "/nix/store/rz8zx6q3gmxn3zsd3p4jvzyznqhm055a-qtshadertools-6.10.2/bin/"
      - "/nix/store/4z51xyah9h8h3al1wclvgy6cb04vq0vl-qtdeclarative-6.10.2/bin/"
      - "/nix/store/b3rx5wac9hhfxn9120xkcvdwj51mc9z2-findutils-4.10.0/bin/"
      - "/nix/store/icrrz26xbyp293kagrlkab1bhc6gra0r-diffutils-3.12/bin/"
      - "/nix/store/wv7qq5yb8plyhxji9x3r5gpkyfm2kf29-gnused-4.9/bin/"
      - "/nix/store/8laf6k81j9ckylrigj3xsk76j69knhvl-gnugrep-3.12/bin/"
      - "/nix/store/gf7b4yz4vhd0y2hnnrimhh875ghwzzzj-gawk-5.3.2/bin/"
      - "/nix/store/isva9q9zx3frx6hh6cnpihh1kd2bx6bk-gnutar-1.35/bin/"
      - "/nix/store/w1n7yp2vnldr395hbwbcaw9sflh413bm-gzip-1.14/bin/"
      - "/nix/store/0xw6y53ijaqwfd9c99wyaqiinychzv1f-gnumake-4.4.1/bin/"
      - "/nix/store/2hjsch59amjs3nbgh7ahcfzm2bfwl8zi-bash-5.3p9/bin/"
      - "/nix/store/8y5jm97n4lyw80gh71yihghbhqc11fdz-patch-2.8/bin/"
      - "/nix/store/27fx8p4k6098wan3zahdbyj79ndcn03z-xz-5.8.2-bin/bin/"
      - "/nix/store/p3j7lphwlci13f9w2v4rav6rbvpi80li-file-5.45/bin/"
      - "/home/rohit/personal/diffy/.direnv/bin/"
      - "/home/rohit/.config/carapace/bin/"
      - "/run/wrappers/bin/"
      - "/home/rohit/.nix-profile/bin/"
      - "/nix/profile/bin/"
      - "/home/rohit/.local/state/nix/profile/bin/"
      - "/etc/profiles/per-user/rohit/bin/"
      - "/nix/var/nix/profiles/default/bin/"
      - "/run/current-system/sw/bin/"
      - "/nix/store/9ama4nm6cjgdkw9fwdfqn3h6fg8rb4nd-ghostty-1.2.3/bin/"
    searched_directories:
      - "/home/rohit/.local/bin/uname"
      - "/home/rohit/.bun/bin/uname"
      - "/home/rohit/.codex/tmp/arg0/codex-arg0wGnUG2/uname"
      - "/home/rohit/.bun/install/global/node_modules/@openai/codex-linux-x64/vendor/x86_64-unknown-linux-musl/path/uname"
      - "/nix/store/b87dfjnjvg932xsw4mszjg4qmvrqzlqk-nodejs-22.22.0/bin/uname"
      - "/nix/store/8x49w8i0vafv34rlc6h4a0f7z0z2qpb5-git-2.53.0/bin/uname"
      - "/nix/store/kbw2j1vag664b3sj3rjwz9v53cqx87sb-gcc-wrapper-15.2.0/bin/uname"
      - "/nix/store/sca0pf46jmxva40qahkcwys5c1lvk6n2-gcc-15.2.0/bin/uname"
      - "/nix/store/2c48s343k15i0cmwb9cp1vi6randmzcw-glibc-2.42-51-bin/bin/uname"
    found: "/nix/store/hlxw2q9qansq7bn52xvlb5badw3z1v8s-coreutils-9.10/bin/uname"
    search_context:
      ENV{PATH}:
        - "/home/rohit/.local/bin"
        - "/home/rohit/.bun/bin"
        - "/home/rohit/.local/bin"
        - "/home/rohit/.bun/bin"
        - "/home/rohit/.codex/tmp/arg0/codex-arg0wGnUG2"
        - "/home/rohit/.bun/install/global/node_modules/@openai/codex-linux-x64/vendor/x86_64-unknown-linux-musl/path"
        - "/nix/store/b87dfjnjvg932xsw4mszjg4qmvrqzlqk-nodejs-22.22.0/bin"
        - "/nix/store/8x49w8i0vafv34rlc6h4a0f7z0z2qpb5-git-2.53.0/bin"
        - "/nix/store/kbw2j1vag664b3sj3rjwz9v53cqx87sb-gcc-wrapper-15.2.0/bin"
        - "/nix/store/sca0pf46jmxva40qahkcwys5c1lvk6n2-gcc-15.2.0/bin"
        - "/nix/store/2c48s343k15i0cmwb9cp1vi6randmzcw-glibc-2.42-51-bin/bin"
        - "/nix/store/hlxw2q9qansq7bn52xvlb5badw3z1v8s-coreutils-9.10/bin"
        - "/nix/store/4yi6jj75bb5hhdzpzlxfyf69d35wsf2x-binutils-wrapper-2.44/bin"
        - "/nix/store/9nmzd62x45ayp4vmswvn6z45h6bzrsla-binutils-2.44/bin"
        - "/nix/store/vj8m1cbj1xw2b3j55ppcby5mnchb9iml-gdb-17.1/bin"
        - "/nix/store/dz1lv10zfqhdnpdjqbawdacd6j1328m1-lldb-21.1.8/bin"
        - "/nix/store/x05g7ya1h7r6x0zycxgxd2i85d4h0pnv-rr-5.9.0/bin"
        - "/nix/store/5a55fdw8da21pkd5g2pd1jkj9q06ljb5-strace-6.19/bin"
        - "/nix/store/1m0z4ixir10fg7ba7g131js04bxgv265-cmake-4.1.2/bin"
        - "/nix/store/4siii6hvzs9ymbq37k04vcpx6xnybz21-ninja-1.13.2/bin"
        - "/nix/store/1nv3i8mpypy3d516f4pd95m0w72r73jy-pkg-config-wrapper-0.29.2/bin"
        - "/nix/store/i1bhjxlrci4j824srcihrm95rxbhkf7w-lndir-1.0.5/bin"
        - "/nix/store/ym2nazjm9vqi0md5dw03vsh9zhg4v6q9-wayland-scanner-1.24.0-bin/bin"
        - "/nix/store/590yx3aynyhs48jyk8ip37fk1mjqfhkb-patchelf-0.15.2/bin"
        - "/nix/store/mxylb81fv1n7skrdlrxnpbzf344mkhy4-curl-8.18.0-dev/bin"
        - "/nix/store/3y8jfnbcv230kip514qh2wmfifihzvqp-brotli-1.2.0/bin"
        - "/nix/store/jmbxnc0r2blyjpivvg3gabz6flyzy3bn-krb5-1.22.1-dev/bin"
        - "/nix/store/aaa7ja0i8hjmgvx6c435h5bm5l8d2jyj-krb5-1.22.1/bin"
        - "/nix/store/dajq3vl5b2x5ld7wxiizcf3xss2dj5fy-nghttp2-1.67.1/bin"
        - "/nix/store/3rr54wwd3246s39mc3z9jzyj9577ik9z-libidn2-2.3.8-bin/bin"
        - "/nix/store/9nww32bprhg1rr1qj423xdr5mwnqk93z-openssl-3.6.1-bin/bin"
        - "/nix/store/qvxaabi4w7isbp0vxqqsx4brl5n1qnjh-libpsl-0.21.5/bin"
        - "/nix/store/xks3v41w0rqp27a17kwkybcvr39rxpl8-zstd-1.5.7-bin/bin"
        - "/nix/store/m27kji8vcm9hn8jyn3dxixxkgbs6p0kp-zstd-1.5.7/bin"
        - "/nix/store/50bwm2f9bzx1vn4fbn2azgx76pqngzc2-curl-8.18.0-bin/bin"
        - "/nix/store/6n5mc6pkgdc9sl529n9h0snvp91df7b9-libgit2-1.9.2/bin"
        - "/nix/store/aca95j471nd9bj5q8f6zzhr1hs36cqsw-tree-sitter-0.25.10/bin"
        - "/nix/store/1f6917ky6w2gghw63myngxr2zq2zh8rm-libxml2-2.15.1-dev/bin"
        - "/nix/store/4krj3d6h2xpcdc6a2hphr2i4k6rab9kc-libxml2-2.15.1-bin/bin"
        - "/nix/store/p9485gsvn63zj7jraa5viv7mzn1m5i73-libxslt-1.1.45-dev/bin"
        - "/nix/store/5akzak6yir5qanifyrxh4fazb8vwn85y-libxslt-1.1.45-bin/bin"
        - "/nix/store/k87a0gv4hg1zmm8j5d3ffmxyvhr13i41-sqlite-3.51.2-bin/bin"
        - "/nix/store/x6y6khsf313j6sa6pjcv9ar0k4rkdph1-harfbuzz-12.3.0-dev/bin"
        - "/nix/store/ja1snqi59bxqa00c95iyk9mz67gm1jbj-graphite2-1.3.14/bin"
        - "/nix/store/q151vxaxv1l4hmf7kccgs45h0xcngagp-icu4c-76.1-dev/bin"
        - "/nix/store/w406ywjzdrsh8qncnr22hqyf6a3rvxgk-libjpeg-turbo-3.1.3-bin/bin"
        - "/nix/store/678ygbangkyc4yb5xm7qb4psfpk3vw4c-libpng-apng-1.6.55-dev/bin"
        - "/nix/store/mckjxamkfdij0vy7m3m7dmhwpbmr0zwq-pcre2-10.46-dev/bin"
        - "/nix/store/wf3ks95mgi0nspblgd9h4kkffd2dzjrd-pcre2-10.46-bin/bin"
        - "/nix/store/n97s6g4759lfdhf7fcl01s0yy9sfkk7m-md4c-0.5.2/bin"
        - "/nix/store/p6vpw9wvgj3l1yvw8q225a7j6f0njiwd-libproxy-0.5.12/bin"
        - "/nix/store/j057drxjcwss3k4d6c9glkqaj5cv5wf5-dbus-1.16.2-lib/bin"
        - "/nix/store/c9cnbxhxbagj7gfpc1g5hl4x4f8dzayv-dbus-1.16.2/bin"
        - "/nix/store/jhb15l57qmqxck5ddd1dh2ys729vc8gb-glib-2.86.3-dev/bin"
        - "/nix/store/md592gfars4m9madyrpj9yrq5jhckgjf-gettext-0.26/bin"
        - "/nix/store/h2mc9v6n2rcxk53nxk6gwcg1md581idy-glib-2.86.3-bin/bin"
        - "/nix/store/9b51f94qkn759n1m88raz4f6rmwj31fc-unixODBC-2.3.12/bin"
        - "/nix/store/wxyn8d3m8g4fnn6xazinjwhzhzdg6wib-systemd-259/bin"
        - "/nix/store/ilk5qzvkadnj7lx58hfinfvl7jmhriq6-util-linux-2.41.3-bin/bin"
        - "/nix/store/vkk4sxf0f998s0nlsaz1k78zldy3qcx4-mtdev-1.1.7/bin"
        - "/nix/store/lxwj6idzb1z8k6c4i7vq6hd8zm2krw7j-lksctp-tools-1.0.21/bin"
        - "/nix/store/v23zbl7lbrqdlbnrmivk9jyxd7gl36b1-libselinux-3.8.1-bin/bin"
        - "/nix/store/jxjhvx3bc62iz70dnfl2dvkbrglaf4v2-libsepol-3.8.1-bin/bin"
        - "/nix/store/nvlwzg459z57dsac3r9g3n0glhy4bwsv-lttng-ust-2.14.0-bin/bin"
        - "/nix/store/hk5mbqv61b0lmxnmls3anbmn7w4bbg0f-libdrm-2.4.131-bin/bin"
        - "/nix/store/xzzk980zwrbjm5j1yrxr43q9c7cdas4l-libdatrie-2019-12-20-bin/bin"
        - "/nix/store/374f5mfap8y7i6rzc3qnq249ym1nxfdq-freetype-2.13.3-dev/bin"
        - "/nix/store/x8l7qzpab2gpdrp89g48mxlrsiz4f0gm-bzip2-1.0.8-bin/bin"
        - "/nix/store/g21qfm40ppq15mmz6n8l48m5k26i8ngf-fontconfig-2.17.1-bin/bin"
        - "/nix/store/k1gvr4prs9736r1lhqyy1plxrrvv9b4m-libxkbcommon-1.11.0/bin"
        - "/nix/store/784p3pvhp35icmzh13rwai726j84r2dg-cups-2.4.16-dev/bin"
        - "/nix/store/q8zb95f4m2aahbdi6jl7wh3cjwc4p855-cups-2.4.16/bin"
        - "/nix/store/w4q31b93w262q2b75ri3jc7m3xd4i31h-qtbase-6.10.2/bin"
        - "/nix/store/rz8zx6q3gmxn3zsd3p4jvzyznqhm055a-qtshadertools-6.10.2/bin"
        - "/nix/store/4z51xyah9h8h3al1wclvgy6cb04vq0vl-qtdeclarative-6.10.2/bin"
        - "/nix/store/hlxw2q9qansq7bn52xvlb5badw3z1v8s-coreutils-9.10/bin"
        - "/nix/store/b3rx5wac9hhfxn9120xkcvdwj51mc9z2-findutils-4.10.0/bin"
        - "/nix/store/icrrz26xbyp293kagrlkab1bhc6gra0r-diffutils-3.12/bin"
        - "/nix/store/wv7qq5yb8plyhxji9x3r5gpkyfm2kf29-gnused-4.9/bin"
        - "/nix/store/8laf6k81j9ckylrigj3xsk76j69knhvl-gnugrep-3.12/bin"
        - "/nix/store/gf7b4yz4vhd0y2hnnrimhh875ghwzzzj-gawk-5.3.2/bin"
        - "/nix/store/isva9q9zx3frx6hh6cnpihh1kd2bx6bk-gnutar-1.35/bin"
        - "/nix/store/w1n7yp2vnldr395hbwbcaw9sflh413bm-gzip-1.14/bin"
        - "/nix/store/x8l7qzpab2gpdrp89g48mxlrsiz4f0gm-bzip2-1.0.8-bin/bin"
        - "/nix/store/0xw6y53ijaqwfd9c99wyaqiinychzv1f-gnumake-4.4.1/bin"
        - "/nix/store/2hjsch59amjs3nbgh7ahcfzm2bfwl8zi-bash-5.3p9/bin"
        - "/nix/store/8y5jm97n4lyw80gh71yihghbhqc11fdz-patch-2.8/bin"
        - "/nix/store/27fx8p4k6098wan3zahdbyj79ndcn03z-xz-5.8.2-bin/bin"
        - "/nix/store/p3j7lphwlci13f9w2v4rav6rbvpi80li-file-5.45/bin"
        - "/home/rohit/personal/diffy/.direnv/bin"
        - "/home/rohit/.local/bin"
        - "/home/rohit/.bun/bin"
        - "/home/rohit/.config/carapace/bin"
        - "/run/wrappers/bin"
        - "/home/rohit/.nix-profile/bin"
        - "/nix/profile/bin"
        - "/home/rohit/.local/state/nix/profile/bin"
        - "/etc/profiles/per-user/rohit/bin"
        - "/nix/var/nix/profiles/default/bin"
        - "/run/current-system/sw/bin"
        - "/nix/store/9ama4nm6cjgdkw9fwdfqn3h6fg8rb4nd-ghostty-1.2.3/bin"
  -
    kind: "message-v1"
    backtrace:
      - "/nix/store/1m0z4ixir10fg7ba7g131js04bxgv265-cmake-4.1.2/share/cmake-4.1/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.18.7 - x86_64
...
